language: node_js
node_js:
  - '12.13.1'
script:
  - echo "Running tests against $(node -v) ..."
  - npm test

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

jobs:
  include:
    - stage: lint
      script:
        - echo "lint start"
        - npm run lint
    - stage: npm release
      script:
        - echo "Deploying to npm ..."
        - npm run build
      deploy:
        provider: npm
        edge: true
        email: info@ateliee.com
        access: public
        on:
          branch: master
          tags: true
        api_key: $NPM_TOKEN

