language: node_js
node_js:
  - '12.13.1'
  - '14.5.0'
script:
  - echo "Running tests against $(node -v) ..."
  - npm test
jobs:
  include:
    - stage: lint
      script:
        - echo "lint start"
        - npm run lint
    - stage: github package release
      script:
        - echo "Deploying to github ..."
        - npm run build
      env:
        - NODE_AUTH_TOKEN=${GITHUB_TOKEN}
      before_deploy: echo "@ateliee:registry=https://npm.pkg.github.com/" > .npmrc
      deploy:
        provider: npm
        edge: true
        email: info@ateliee.com
        access: public
        on:
          branch: master
        api_key: $GITHUB_TOKEN
    - stage: npm package release
      script:
        - echo "Deploying to npm ..."
        - npm run build
      env:
        - NODE_AUTH_TOKEN=${NPM_TOKEN}
      before_deploy: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      deploy:
        provider: npm
        edge: true
        email: info@ateliee.com
        access: public
        on:
          branch: master
        api_key: $NPM_TOKEN